# Usa l'immagine Node.js come base
FROM node:20-alpine

# Installa pacchetti necessari per compilare moduli nativi
RUN apk add --no-cache iputils curl 
RUN apk add --no-cache python3 make g++ bash

# Abilita Yarn tramite Corepack
RUN corepack enable

# Aggiungi un argomento di build per configurare la porta
ARG APP_PORT

# Espone la porta dinamicamente in base al valore dell'argomento
ENV PORT=$APP_PORT
EXPOSE $PORT